### PR TITLE
Password field doesn't populate to config file.

### PR DESCRIPTION
**Pull request by NobodyCentral**
As is, the egg doesn't set the server password. This is due to a typo when ptero writes the fields to the files. Right now it tries to write the env var named SERVER_PWD to the config file, but that's not the right env var. The correct one is SERVER_PASS. This results in the server pass being empty no matter what. As you can see in the proposed pull this fixes that.

This is my first pull request to someone else's repo, sorry if it's sloppy.

### CODE REVIEW

**Comment by ImKringle** [comment]
Ah, yep that's a fat typo haha!

Looks good to me, but if you could please make sure the Exported Timestamp is updated as well
```
    "exported_at": "2024-04-22T04:19:51-04:00",
```
^ Would need updated to whenever your egg was exported from your panel

Thanks!

**Comment by NobodyCentral** [comment]
Shoot, forgot to update the timestamp, I'll do that. Also, I noticed something else. The steam ID field is incorrect. Astroneer doesn't use steam's ID system, so may I also update the field to accept an Astroneer ID instead of steam's? It would just involve a quick title and description change... it would also have to be changed to a numeric input because Astroneer uses IDs beyond the 32bit integer limit.

**Review by ImKringle — APPROVED** [review]

**Comment by ImKringle** [comment]
Im currently working on updating the egg/image to use the pre-created executable from JoeJoe, so I'll get that updated; since by default it ideally should be 0 with a note it uses a Astroneer ID not Steam. Good call!

Merging in, I'll probably have a egg/image update out in a few hours so yours may need an update when that happens. LGTM!

**Comment by NobodyCentral** [comment]
The reason why I like setting the astro ID and not leaving it as 0 is because theoretically someone could just change their steam display name to be the same as your own, which would give them admin.

But yeah to make the Astro ID field work it has to be numeric; reading over the ptero docs, I don't think there are any other var types that will handle that long of a UUID, besides a string maybe, but numeric is just better for this. I've actually patched this in locally on the egg I'm using and it works.

**Comment by ImKringle** [comment]
Fixed and pushed, might wanna update the egg ✔️

**Pull request merged**
